export type ScrapeSourceJob = {
  source: string;
  runId?: string;
  sourceRunId?: string;
  requestId?: string;
  callbackUrl?: string;
  callbackToken?: string;
  userId?: string;
  careerProfileId?: string;
  listingUrl?: string;
  limit?: number;
  filters?: {
    specializations?: string[];
    workModes?: string[];
    workDimensions?: string[];
    location?: string;
    radiusKm?: number;
    publishedWithinDays?: number;
    positionLevels?: string[];
    contractTypes?: string[];
    technologies?: string[];
    salaryMin?: number;
    onlyWithProjectDescription?: boolean;
    onlyEmployerOffers?: boolean;
    ukrainiansWelcome?: boolean;
    noPolishRequired?: boolean;
    categories?: string[];
    employmentTypes?: string[];
    experienceLevels?: string[];
    keywords?: string;
  };
};
