import { ApiProperty } from '@nestjs/swagger';
import { IsInt, IsOptional, IsString, IsUUID, Min } from 'class-validator';

export class ScrapeCompleteDto {
  @ApiProperty({ description: 'Job source run id generated by DB' })
  @IsUUID('4')
  sourceRunId!: string;

  @ApiProperty({ description: 'Worker run id', required: false })
  @IsOptional()
  @IsString()
  runId?: string;

  @ApiProperty({ description: 'Number of job offers scraped', required: false })
  @IsOptional()
  @IsInt()
  @Min(0)
  jobCount?: number;
}
