import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsIn, IsInt, IsOptional, IsString, IsUUID, MaxLength, Min } from 'class-validator';

const SCRAPE_COMPLETE_STATUS = ['COMPLETED', 'FAILED'] as const;

export class ScrapeCompleteDto {
  @ApiProperty({ description: 'Job source run id generated by DB' })
  @IsUUID('4')
  sourceRunId!: string;

  @ApiPropertyOptional({ description: 'Worker run id' })
  @IsOptional()
  @IsString()
  runId?: string;

  @ApiPropertyOptional({ description: 'Worker terminal status', enum: SCRAPE_COMPLETE_STATUS, default: 'COMPLETED' })
  @IsOptional()
  @IsIn(SCRAPE_COMPLETE_STATUS)
  status?: (typeof SCRAPE_COMPLETE_STATUS)[number];

  @ApiPropertyOptional({ description: 'Number of scraped job offers (legacy alias)', minimum: 0 })
  @IsOptional()
  @IsInt()
  @Min(0)
  jobCount?: number;

  @ApiPropertyOptional({ description: 'Number of scraped job offers', minimum: 0 })
  @IsOptional()
  @IsInt()
  @Min(0)
  scrapedCount?: number;

  @ApiPropertyOptional({ description: 'Number of discovered job links', minimum: 0 })
  @IsOptional()
  @IsInt()
  @Min(0)
  totalFound?: number;

  @ApiPropertyOptional({ description: 'Failure reason when status=FAILED' })
  @IsOptional()
  @IsString()
  @MaxLength(1000)
  error?: string;
}
