@host = http://localhost:3000
@apiPrefix = api
@baseUrl = {{host}}/{{apiPrefix}}
@accessToken = replace_with_access_token

### Get current user (auth)
GET {{baseUrl}}/user
Authorization: Bearer {{accessToken}}