export type TesterService = 'api' | 'worker';

export type TesterEndpointPreset = {
  id: string;
  label: string;
  service: TesterService;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  requiresAuth?: boolean;
  defaultBody?: Record<string, unknown>;
  notes?: string;
};

export const testerEndpointPresets: TesterEndpointPreset[] = [
  {
    id: 'api-health',
    label: 'API: health',
    service: 'api',
    method: 'GET',
    path: '/health',
  },
  {
    id: 'api-health-test',
    label: 'API: health/test',
    service: 'api',
    method: 'GET',
    path: '/health/test',
  },
  {
    id: 'auth-register',
    label: 'Auth: register',
    service: 'api',
    method: 'POST',
    path: '/auth/register',
    defaultBody: {
      email: 'tester@example.com',
      password: 'Test12345!',
      confirmPassword: 'Test12345!',
      code: '000000',
    },
  },
  {
    id: 'auth-login',
    label: 'Auth: login',
    service: 'api',
    method: 'POST',
    path: '/auth/login',
    defaultBody: {
      email: 'tester@example.com',
      password: 'Test12345!',
    },
  },
  {
    id: 'auth-logout',
    label: 'Auth: logout',
    service: 'api',
    method: 'POST',
    path: '/auth/logout',
    requiresAuth: true,
  },
  {
    id: 'auth-send-register-code',
    label: 'Auth: send-register-code',
    service: 'api',
    method: 'POST',
    path: '/auth/send-register-code',
    defaultBody: { email: 'tester@example.com' },
  },
  {
    id: 'auth-send-reset-code',
    label: 'Auth: send-reset-password-code',
    service: 'api',
    method: 'POST',
    path: '/auth/send-reset-password-code',
    defaultBody: { email: 'tester@example.com' },
  },
  {
    id: 'auth-change-password',
    label: 'Auth: change-password',
    service: 'api',
    method: 'POST',
    path: '/auth/change-password',
    requiresAuth: true,
    defaultBody: {
      oldPassword: 'Test12345!',
      newPassword: 'Test123456!',
      confirmPassword: 'Test123456!',
    },
  },
  {
    id: 'auth-reset-password',
    label: 'Auth: reset-password',
    service: 'api',
    method: 'POST',
    path: '/auth/reset-password',
    defaultBody: {
      email: 'tester@example.com',
      code: '000000',
      password: 'Test12345!',
      confirmPassword: 'Test12345!',
    },
  },
  {
    id: 'user-me',
    label: 'User: current user',
    service: 'api',
    method: 'GET',
    path: '/user',
    requiresAuth: true,
  },
  {
    id: 'profile-input-create',
    label: 'Profile Inputs: create',
    service: 'api',
    method: 'POST',
    path: '/profile-inputs',
    requiresAuth: true,
    defaultBody: {
      targetRoles: 'Backend Developer, NestJS Engineer',
      notes: 'Remote-first, TypeScript stack, Poland timezone',
    },
  },
  {
    id: 'profile-input-latest',
    label: 'Profile Inputs: latest',
    service: 'api',
    method: 'GET',
    path: '/profile-inputs/latest',
    requiresAuth: true,
  },
  {
    id: 'onboarding-draft-get',
    label: 'Onboarding: get draft',
    service: 'api',
    method: 'GET',
    path: '/onboarding/draft',
    requiresAuth: true,
  },
  {
    id: 'onboarding-draft-upsert',
    label: 'Onboarding: upsert draft',
    service: 'api',
    method: 'PUT',
    path: '/onboarding/draft',
    requiresAuth: true,
    defaultBody: {
      stepOne: {
        desiredRole: 'Frontend Developer',
        desiredSpecialization: 'IT - Rozwój oprogramowania',
        preferredLocations: ['Gdynia'],
        workModes: ['hybrid', 'home-office'],
        keywords: ['react', 'typescript', 'next.js'],
        seniorities: ['junior'],
      },
      stepTwo: {
        notes:
          'Open to remote-first offers, can relocate in Tricity area for hybrid.',
      },
    },
  },
  {
    id: 'onboarding-draft-delete',
    label: 'Onboarding: delete draft',
    service: 'api',
    method: 'DELETE',
    path: '/onboarding/draft',
    requiresAuth: true,
  },
  {
    id: 'documents-list',
    label: 'Documents: list',
    service: 'api',
    method: 'GET',
    path: '/documents',
    requiresAuth: true,
  },
  {
    id: 'documents-upload-health',
    label: 'Documents: upload health',
    service: 'api',
    method: 'GET',
    path: '/documents/upload-health',
    requiresAuth: true,
  },
  {
    id: 'documents-create-upload-url',
    label: 'Documents: create upload URL',
    service: 'api',
    method: 'POST',
    path: '/documents/upload-url',
    requiresAuth: true,
    defaultBody: {
      type: 'CV',
      originalName: 'cv.pdf',
      mimeType: 'application/pdf',
      size: 1024,
    },
    notes: 'Use response.document.id for confirm/extract endpoints.',
  },
  {
    id: 'documents-confirm',
    label: 'Documents: confirm upload',
    service: 'api',
    method: 'POST',
    path: '/documents/confirm',
    requiresAuth: true,
    defaultBody: {
      documentId: '<document-id>',
    },
  },
  {
    id: 'documents-extract',
    label: 'Documents: extract text',
    service: 'api',
    method: 'POST',
    path: '/documents/extract',
    requiresAuth: true,
    defaultBody: {
      documentId: '<document-id>',
    },
  },
  {
    id: 'documents-sync',
    label: 'Documents: sync with storage',
    service: 'api',
    method: 'POST',
    path: '/documents/sync',
    requiresAuth: true,
    defaultBody: {
      dryRun: true,
    },
  },
  {
    id: 'document-by-id',
    label: 'Documents: get by id',
    service: 'api',
    method: 'GET',
    path: '/documents/<document-id>',
    requiresAuth: true,
  },
  {
    id: 'document-events',
    label: 'Documents: diagnostics timeline',
    service: 'api',
    method: 'GET',
    path: '/documents/<document-id>/events',
    requiresAuth: true,
  },
  {
    id: 'document-update',
    label: 'Documents: update metadata',
    service: 'api',
    method: 'PATCH',
    path: '/documents/<document-id>',
    requiresAuth: true,
    defaultBody: {
      type: 'CV',
      originalName: 'cv-updated.pdf',
    },
  },
  {
    id: 'document-delete',
    label: 'Documents: delete',
    service: 'api',
    method: 'DELETE',
    path: '/documents/<document-id>',
    requiresAuth: true,
  },
  {
    id: 'career-profile-generate',
    label: 'Career Profiles: generate',
    service: 'api',
    method: 'POST',
    path: '/career-profiles',
    requiresAuth: true,
    defaultBody: {
      instructions: 'Focus on backend roles and clear strengths list.',
    },
  },
  {
    id: 'career-profile-latest',
    label: 'Career Profiles: latest',
    service: 'api',
    method: 'GET',
    path: '/career-profiles/latest',
    requiresAuth: true,
  },
  {
    id: 'career-profile-list',
    label: 'Career Profiles: list',
    service: 'api',
    method: 'GET',
    path: '/career-profiles',
    requiresAuth: true,
  },
  {
    id: 'career-profile-quality',
    label: 'Career Profiles: quality diagnostics',
    service: 'api',
    method: 'GET',
    path: '/career-profiles/quality',
    requiresAuth: true,
  },
  {
    id: 'career-profile-by-id',
    label: 'Career Profiles: get by id',
    service: 'api',
    method: 'GET',
    path: '/career-profiles/<profile-id>',
    requiresAuth: true,
  },
  {
    id: 'career-profile-restore',
    label: 'Career Profiles: restore version',
    service: 'api',
    method: 'POST',
    path: '/career-profiles/<profile-id>/restore',
    requiresAuth: true,
  },
  {
    id: 'career-profile-documents',
    label: 'Career Profiles: list profile documents',
    service: 'api',
    method: 'GET',
    path: '/career-profiles/<profile-id>/documents',
    requiresAuth: true,
  },
  {
    id: 'job-matching-score',
    label: 'Job Matching: score free-text job',
    service: 'api',
    method: 'POST',
    path: '/job-matching/score',
    requiresAuth: true,
    defaultBody: {
      jobDescription: 'Backend Node.js role requiring NestJS, PostgreSQL, AWS.',
      minScore: 50,
    },
  },
  {
    id: 'job-matching-list',
    label: 'Job Matching: list history',
    service: 'api',
    method: 'GET',
    path: '/job-matching',
    requiresAuth: true,
  },
  {
    id: 'job-matching-by-id',
    label: 'Job Matching: get history item',
    service: 'api',
    method: 'GET',
    path: '/job-matching/<match-id>',
    requiresAuth: true,
  },
  {
    id: 'job-offers-list',
    label: 'Job Offers: list',
    service: 'api',
    method: 'GET',
    path: '/job-offers?mode=strict&limit=20&offset=0',
    requiresAuth: true,
  },
  {
    id: 'workspace-summary',
    label: 'Workspace: summary',
    service: 'api',
    method: 'GET',
    path: '/workspace/summary',
    requiresAuth: true,
  },
  {
    id: 'job-offers-status-history',
    label: 'Job Offers: status history',
    service: 'api',
    method: 'GET',
    path: '/job-offers/status-history?limit=20&offset=0',
    requiresAuth: true,
  },
  {
    id: 'job-offers-item-history',
    label: 'Job Offers: offer status history',
    service: 'api',
    method: 'GET',
    path: '/job-offers/<offer-id>/history',
    requiresAuth: true,
  },
  {
    id: 'job-offers-update-status',
    label: 'Job Offers: update status',
    service: 'api',
    method: 'PATCH',
    path: '/job-offers/<offer-id>/status',
    requiresAuth: true,
    defaultBody: {
      status: 'SAVED',
    },
  },
  {
    id: 'job-offers-update-meta',
    label: 'Job Offers: update meta',
    service: 'api',
    method: 'PATCH',
    path: '/job-offers/<offer-id>/meta',
    requiresAuth: true,
    defaultBody: {
      notes: 'Interesting backend role with modern stack',
      tags: ['backend', 'nestjs'],
    },
  },
  {
    id: 'job-offers-score',
    label: 'Job Offers: score persisted offer',
    service: 'api',
    method: 'POST',
    path: '/job-offers/<offer-id>/score',
    requiresAuth: true,
    defaultBody: {
      minScore: 50,
    },
  },
  {
    id: 'job-sources-scrape',
    label: 'Job Sources: enqueue scrape',
    service: 'api',
    method: 'POST',
    path: '/job-sources/scrape',
    requiresAuth: true,
    defaultBody: {
      source: 'pracuj-pl-it',
      limit: 10,
      filters: {
        specializations: ['backend', 'frontend'],
        workModes: ['hybrid', 'home-office'],
        positionLevels: ['4', '18'],
        salaryMin: 10000,
      },
    },
  },
  {
    id: 'job-sources-runs',
    label: 'Job Sources: list runs',
    service: 'api',
    method: 'GET',
    path: '/job-sources/runs',
    requiresAuth: true,
  },
  {
    id: 'job-sources-run-by-id',
    label: 'Job Sources: get run by id',
    service: 'api',
    method: 'GET',
    path: '/job-sources/runs/<run-id>',
    requiresAuth: true,
  },
  {
    id: 'job-sources-run-diagnostics',
    label: 'Job Sources: get run diagnostics',
    service: 'api',
    method: 'GET',
    path: '/job-sources/runs/<run-id>/diagnostics',
    requiresAuth: true,
  },
  {
    id: 'worker-health',
    label: 'Worker: health',
    service: 'worker',
    method: 'GET',
    path: '/health',
  },
  {
    id: 'worker-task-envelope',
    label: 'Worker: enqueue task (envelope)',
    service: 'worker',
    method: 'POST',
    path: '/tasks',
    defaultBody: {
      name: 'scrape:source',
      payload: {
        source: 'pracuj-pl-it',
        limit: 5,
      },
    },
    notes: 'Adds task directly to worker queue; API is bypassed.',
  },
  {
    id: 'worker-task-payload',
    label: 'Worker: enqueue task (payload shortcut)',
    service: 'worker',
    method: 'POST',
    path: '/tasks',
    defaultBody: {
      source: 'pracuj-pl-it',
      limit: 5,
      filters: {
        specializations: ['backend'],
      },
    },
  },
  {
    id: 'worker-scrape-alias',
    label: 'Worker: enqueue via /scrape alias',
    service: 'worker',
    method: 'POST',
    path: '/scrape',
    defaultBody: {
      source: 'pracuj-pl-it',
      limit: 5,
    },
  },
  {
    id: 'worker-callback-replay',
    label: 'Worker: replay callback dead letters',
    service: 'worker',
    method: 'POST',
    path: '/callbacks/replay',
    notes: 'Replays files from WORKER_DEAD_LETTER_DIR to API callback endpoint.',
  },
];
